---
- name: configure spines
  hosts: spines
  become: yes
  vars_files:
    - vars.yml
  tasks:
  - name: configure spines for BGP Unnumbered (BGP config)
    nclu:
      commands:
      - add loopback lo ip address {{ devices[ansible_hostname].loopback }}
      - add bgp autonomous-system {{ devices[ansible_hostname].as }}

  - name: Configure bgp neighbors
    nclu:
      commands:
      - add bgp neighbor {{ item }} interface remote-as external
      - add bgp neighbor {{ item }} capability extended-nexthop
      commit: true
    with_items: "{{ devices[ansible_hostname].leaf_ports }}"



- name: configure Leafs
  hosts: leafs
  become: yes
  vars_files:
  - vars.yml
    
  tasks:
    - name: configure leafs for BGP Unnumbered (BGP config)
      nclu:
        commands:
        - add loopback lo ip address {{ devices[ansible_hostname].loopback }}
        - add bgp autonomous-system {{ devices[ansible_hostname].as }}
  
    - name: Configure bgp neighbors
      nclu:
        commands:
        - add bgp neighbor {{ item }} interface remote-as external
        - add bgp neighbor {{ item }} capability extended-nexthop
        commit: true
      with_items: "{{ devices[ansible_hostname].spine_ports }}"


