---
- name: Setup tasks
  hosts: leafs,spines
  become: yes
  vars_files:
    - var.yml
  
  tasks:
  - name: Configure hostname on all switches
    nclu:
      commands:
      - add hostname {{ devices[ansible_hostname].hostname }}
      atomic: true
