---
    - name: delete config
      hosts: leaf01:leaf02:spine01
      become: yes
      nclu:
        commands:
          - del all
        atomic: true
  
    - name: Configure leafs
      hosts: leaf01:leaf02
      become: yes
      vars_files:
        - simple-network-vars.yml
      
      tasks:
      - name: Configure leafs
        nclu:
          commands:
          - add bridge bridge vids 10,20
          - add bridge bridge ports swp10
          - add interface swp1 bridge access 10
          atomic: true

    - name: configure spines
      hosts: spine01
      become: yes
      vars_files:
        - simple-network-vars.yml

      tasks:
      - name: configure spines
        nclu:
          commands:
          - add bridge bridge vids 10,20
          - add bridge bridge ports swp1,swp2
          - add vlan 10 ip address 192.168.10.1/24
          atomic: true
        